//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiamondShopBOs
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNotification
    {
        public string notificationID { get; set; }
        public string userID { get; set; }
        public System.DateTime date { get; set; }
        public string detail { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
