//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiamondShopBOs
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderStatusUpdate
    {
        public int updateID { get; set; }
        public string orderID { get; set; }
        public string status { get; set; }
        public System.DateTime updateTime { get; set; }
    
        public virtual tblOrder tblOrder { get; set; }
    }
}
