//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiamondShopBOs
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOrder()
        {
            this.tblOrderItems = new HashSet<tblOrderItem>();
            this.tblOrderStatusUpdates = new HashSet<tblOrderStatusUpdate>();
            this.tblTransactions = new HashSet<tblTransaction>();
        }
    
        public string orderID { get; set; }
        public string customerID { get; set; }
        public string deliveryStaffID { get; set; }
        public string saleStaffID { get; set; }
        public double totalMoney { get; set; }
        public double paidAmount { get; set; }
        public double remainingAmount { get; set; }
        public string status { get; set; }
        public string paymentStatus { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public System.DateTime saleDate { get; set; }
        public string customerName { get; set; }
        public Nullable<int> voucherID { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        public virtual tblUser tblUser2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderItem> tblOrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderStatusUpdate> tblOrderStatusUpdates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTransaction> tblTransactions { get; set; }
    }
}
