//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiamondShopBOs
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransaction
    {
        public int transactionID { get; set; }
        public string orderID { get; set; }
        public string userID { get; set; }
        public string transactionType { get; set; }
        public System.DateTime transactionDate { get; set; }
        public double amount { get; set; }
        public string paymentMethod { get; set; }
    
        public virtual tblOrder tblOrder { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
