//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiamondShopBOs
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWarranty
    {
        public int warrantyID { get; set; }
        public string orderID { get; set; }
        public int ItemID { get; set; }
        public System.DateTime warrantyStartDate { get; set; }
        public System.DateTime warrantyEndDate { get; set; }
        public string warrantyDetails { get; set; }
    
        public virtual tblOrderItem tblOrderItem { get; set; }
    }
}
